### ISSUE TITLE
Cannot properly install on Mac

### ISSUE THREAD

**Issue by JudgeGroovyman** [woden-engine/woden#23]
Using fresh 9.0 Stable or 10.0 Development images on Mac (Big Sur and Monterey on a 2017 MBP which supports Metal) I am unable to run the example program `WDASolidColorViewSample` listed in the main repo readme.  

Clues:
1. I did nothing special: New clean image, open a transcript, run the metacello command from the main repo readme in a playground.
1. During install an error popup shows up in the bottom left but I am unable to click it fast enough to see what it was and the transcript doesnt show any errors. 
2. There are hundreds of what appear to be warnings in the transcript that say `_____ is Undeclared`
3. When I run the WDASolidColorViewSample program listed in the main repo readme a blank black square graphics window appears and I get the following debugger:  `"Instance of WDAOSWindowViewWindow did not understand #renderTarget"` and the new graphics window cannot be closed
4. If I run the WDASolidColorViewSample program again it does not bring up a new window or a new debugger
5. `WDASceneExamples example01Cube.` also opens a blank black square graphics window, but no error this time.
6. Using 10.0 Development image I got the following error during installation that I didnt get using 9.0 `"Warning: This package depends on the following classes:   GLMBrickRenderer   GLMBrick   GLMStringBrick   GLMInteractableBrickRenderer You must resolve these dependencies before you will be able to load these definitions:    GLMBrick>>#buildChildrenSceneGraphNodeWith:   GLMBrick>>#buildSceneGraphNodeWith:   GLMBrick>>#onBuildSceneGraphNodeWith:   GLMBrickRenderer>>#buildBackgroundColorSceneGraphNodeFor:in:with:   GLMBrickRenderer>>#buildBackgroundColorSceneGraphNodeFor:with:   GLMBrickRenderer>>#buildBorderSceneGraphNodeFor:with:   GLMBrickRenderer>>#buildSceneGraphNodeFor:with:   GLMBrickRenderer>>#buildShadowSceneGraphNodeFor:with:   GLMInteractableBrickRenderer>>#buildColorSceneGraphNodeFor:with:   GLMInteractableBrickRenderer>>#buildImageSceneGraphNodeFor:with:   GLMInteractableBrickRenderer>>#buildSceneGraphNodeFor:with:   GLMStringBrick>>#onBuildSceneGraphNodeWith: "self`

**Comment by ronsaldo** [comment]
I have just pushed the missing commits from my personal branch. That should fix the loading issues in Pharo 9. Currently I am working on a completely clean rewrite of this with a focus on modularity and stability on separate repositories, so, do not expect more updates on this repo until I announce the new version with proper demos.

**Comment by JudgeGroovyman** [comment]
Github doesn't show any changes since July 14 and it still doesn't load in Pharo 9 am I looking in the right place?    

Looking forward to the new repo with the clean rewrite.  that sounds cool!   Thanks for working on this.
